// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lrxpkqcaecrighcxdkjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyeHBrcWNhZWNyaWdoY3hka2pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0MzE3NDMsImV4cCI6MjA3NjAwNzc0M30.HrQHHSE2kedK9Pdn7ufYAl5D2m16etoxUAyFsnaUJ74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);